/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Prabhakar
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_addMenu = new javax.swing.JMenuItem();
        jMenuItem_viewMenu = new javax.swing.JMenuItem();
        jMenu_viewWaiter = new javax.swing.JMenu();
        jMenuItem_addWaiter = new javax.swing.JMenuItem();
        jMenuItem_viewWaiter = new javax.swing.JMenuItem();
        jMenu_viewTable = new javax.swing.JMenu();
        jMenuItem_addTable = new javax.swing.JMenuItem();
        jMenuItem_viewTable = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jMenu1.setText("Menu");

        jMenuItem_addMenu.setText("Add Menu");
        jMenuItem_addMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addMenuActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_addMenu);

        jMenuItem_viewMenu.setText("View Menu");
        jMenuItem_viewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_viewMenuActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_viewMenu);

        jMenuBar1.add(jMenu1);

        jMenu_viewWaiter.setText("Waiter");

        jMenuItem_addWaiter.setText("Add Waiter");
        jMenuItem_addWaiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addWaiterActionPerformed(evt);
            }
        });
        jMenu_viewWaiter.add(jMenuItem_addWaiter);

        jMenuItem_viewWaiter.setText("View Waiter");
        jMenuItem_viewWaiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_viewWaiterActionPerformed(evt);
            }
        });
        jMenu_viewWaiter.add(jMenuItem_viewWaiter);

        jMenuBar1.add(jMenu_viewWaiter);

        jMenu_viewTable.setText("Table");
        jMenu_viewTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_viewTableActionPerformed(evt);
            }
        });

        jMenuItem_addTable.setText("Add Table");
        jMenuItem_addTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addTableActionPerformed(evt);
            }
        });
        jMenu_viewTable.add(jMenuItem_addTable);

        jMenuItem_viewTable.setText("View Table");
        jMenuItem_viewTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_viewTableActionPerformed(evt);
            }
        });
        jMenu_viewTable.add(jMenuItem_viewTable);

        jMenuBar1.add(jMenu_viewTable);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_addMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_addMenuActionPerformed
        // TODO add your handling code here:
        AddMenu adm=new AddMenu();
        desktop.add(adm);
        adm.show();
    }//GEN-LAST:event_jMenuItem_addMenuActionPerformed

    private void jMenuItem_viewWaiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_viewWaiterActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenuItem_viewWaiterActionPerformed

    private void jMenuItem_viewTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_viewTableActionPerformed
        // TODO add your handling code here:
        ViewTable vw=new ViewTable();
        desktop.add(vw);
        vw.show();
    }//GEN-LAST:event_jMenuItem_viewTableActionPerformed

    private void jMenuItem_addWaiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_addWaiterActionPerformed
        // TODO add your handling code here:
        AddWaiter adw=new AddWaiter();
        desktop.add(adw);
        adw.show();
    }//GEN-LAST:event_jMenuItem_addWaiterActionPerformed

    private void jMenuItem_addTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_addTableActionPerformed
        // TODO add your handling code here:
        AddTable adt=new AddTable();
        desktop.add(adt);
        adt.show();
    }//GEN-LAST:event_jMenuItem_addTableActionPerformed

    private void jMenuItem_viewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_viewMenuActionPerformed
        // TODO add your handling code here:
        ViewMenu vm=new ViewMenu();
        desktop.add(vm);
        vm.show();
    }//GEN-LAST:event_jMenuItem_viewMenuActionPerformed

    private void jMenu_viewTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_viewTableActionPerformed
        // TODO add your handling code here:
        ViewTable vt=new ViewTable();
        desktop.add(vt);
        vt.show();
        
    }//GEN-LAST:event_jMenu_viewTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem_addMenu;
    private javax.swing.JMenuItem jMenuItem_addTable;
    private javax.swing.JMenuItem jMenuItem_addWaiter;
    private javax.swing.JMenuItem jMenuItem_viewMenu;
    private javax.swing.JMenuItem jMenuItem_viewTable;
    private javax.swing.JMenuItem jMenuItem_viewWaiter;
    private javax.swing.JMenu jMenu_viewTable;
    private javax.swing.JMenu jMenu_viewWaiter;
    // End of variables declaration//GEN-END:variables
}
