/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ItemDAO;
import controller.OrderDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.AddItem;
import model.AddItemWaiter;
import util.Global;

/**
 *
 * @author Prabhakar
 */
public class ViewMenuWaiter extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewMenuWaiter
     */
    int rowval=0;
    int tablevalue=0; //checking whether the waiter come in same jTextfield for edit or new insert
    DefaultTableModel model;
    DefaultTableModel model1;
    public ViewMenuWaiter() {
        initComponents();
        jLabel_table.setText(Global.table_name);    //for displaaying table name and waiter name in viewmenuwaiter form in jlabel
        jLabel_waiter.setText(Global.waiter_name);
//        AddItemWaiter aiw=new AddItemWaiter();
        
        
        
        
        model = new DefaultTableModel(null,new String[]{"ID","Item Name","Price"});
        jTable_viewMenu.setModel(model);
        
        
        model1 = new DefaultTableModel(null,new String[]{"ID","Item Name","Price","qty"});
        jTable_orderItem.setModel(model1);
        
        
    }
    public void clearTable()
    {
        int row=jTable_viewMenu.getRowCount();
        for(int i=0;i<row;i++)
        {
            model.removeRow(0);
        }
    }
    public void clearTable1()
    {
        int row=jTable_orderItem.getRowCount();
        for(int i=0;i<row;i++)
        {
            model1.removeRow(0);
        }
    }
    public void clearField()
    {
        jTextField_idMenu.setText("");
        jTextField_itemName.setText("");
        jTextField_price.setText("");
        jTextField_qty.setText("");
    }
    /*public List<AddItemWaiter> getItem()
    {
        List<AddItemWaiter> laiw=new ArrayList();
        try
        {

        int id1=Integer.parseInt(jTextField_idMenu.getText());
        String name=jTextField_itemName.getText();
        String price=jTextField_price.getText();
        String qty=jTextField_qty.getText();
        AddItemWaiter aiw=new AddItemWaiter();
        aiw.setId(id1);
        aiw.setName(name);
        aiw.setPrice(price);
        aiw.setQty(qty);
        
        laiw.add(aiw);
        
        
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
        return laiw;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_loadMenu = new javax.swing.JButton();
        jLabel_table = new javax.swing.JLabel();
        jLabel_waiter = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_orderItem = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton_confirmOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_viewMenu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_addItem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField_idMenu = new javax.swing.JTextField();
        jTextField_itemName = new javax.swing.JTextField();
        jTextField_price = new javax.swing.JTextField();
        jTextField_qty = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jButton_loadMenu.setText("Load Menu");
        jButton_loadMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loadMenuActionPerformed(evt);
            }
        });

        jLabel_table.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_table.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_table.setText("jLabel1");

        jLabel_waiter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_waiter.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_waiter.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Table :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name :");

        jTable_orderItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_orderItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_orderItemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_orderItem);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ordered Items");

        jButton_confirmOrder.setBackground(new java.awt.Color(204, 0, 0));
        jButton_confirmOrder.setText("Confirm Order??");
        jButton_confirmOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_confirmOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_table))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_waiter))
                    .addComponent(jButton_loadMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_confirmOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_loadMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_table))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_waiter))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_confirmOrder)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTable_viewMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_viewMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_viewMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_viewMenu);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Item Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");

        jButton_addItem.setText(" Add This Item");
        jButton_addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addItemActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Qty");

        jTextField_idMenu.setEditable(false);
        jTextField_idMenu.setText(" ");

        jTextField_itemName.setEditable(false);
        jTextField_itemName.setText(" ");

        jTextField_price.setEditable(false);
        jTextField_price.setText(" ");

        jTextField_qty.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_addItem)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_idMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_idMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_addItem)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_loadMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loadMenuActionPerformed
        // TODO add your handling code here:
        clearTable();
        ItemDAO idao=new ItemDAO();
        List<AddItem> lai=idao.getMenu();
        for(AddItem ai:lai)
        {
            model.addRow(new Object[]{ai.getId(),ai.getItemName(),ai.getPrice()});
        }
    }//GEN-LAST:event_jButton_loadMenuActionPerformed

    private void jTable_viewMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_viewMenuMouseClicked
        // TODO add your handling code here:
        int row=jTable_viewMenu.getSelectedRow();
        jTextField_idMenu.setText(jTable_viewMenu.getValueAt(row, 0).toString());
        jTextField_itemName.setText(jTable_viewMenu.getValueAt(row, 1).toString());
        jTextField_price.setText(jTable_viewMenu.getValueAt(row, 2).toString());
        
    }//GEN-LAST:event_jTable_viewMenuMouseClicked

    private void jButton_addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addItemActionPerformed
        // TODO add your handling code here:
        if(tablevalue>0)    // checking whether the waiter come in same jTextfield for edit or new insert
        {
        model1.removeRow(rowval);
        int id1=Integer.parseInt(jTextField_idMenu.getText());
        String name=jTextField_itemName.getText();
        String price=jTextField_price.getText();
        String qty=jTextField_qty.getText();
        AddItemWaiter aiw=new AddItemWaiter();
        aiw.setId(id1);
        aiw.setName(name);
        aiw.setPrice(price);
        aiw.setQty(qty);
        
            
        model1.addRow(new Object[]{aiw.getId(),aiw.getName(),aiw.getPrice(),aiw.getQty()});
        
        clearField();
        }
        
        else
        {
        int id1=Integer.parseInt(jTextField_idMenu.getText());
        String name=jTextField_itemName.getText();
        String price=jTextField_price.getText();
        String qty=jTextField_qty.getText();
        AddItemWaiter aiw=new AddItemWaiter();
        aiw.setId(id1);
        aiw.setName(name);
        aiw.setPrice(price);
        aiw.setQty(qty);
        
            
        model1.addRow(new Object[]{aiw.getId(),aiw.getName(),aiw.getPrice(),aiw.getQty()});
        
        clearField();
        }
    }//GEN-LAST:event_jButton_addItemActionPerformed

    private void jTable_orderItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_orderItemMouseClicked
        // TODO add your handling code here:
        tablevalue=1;
        rowval= jTable_orderItem.getSelectedRow();
        jTextField_idMenu.setText(jTable_orderItem.getValueAt(rowval, 0).toString());
        jTextField_itemName.setText((String) jTable_orderItem.getValueAt(rowval, 1));
        jTextField_price.setText(jTable_orderItem.getValueAt(rowval, 2).toString());
        jTextField_qty.setText(jTable_orderItem.getValueAt(rowval, 3).toString());
    }//GEN-LAST:event_jTable_orderItemMouseClicked

    private void jButton_confirmOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_confirmOrderActionPerformed
        // TODO add your handling code here:
        List<AddItemWaiter> laiw=new ArrayList();
        int row=jTable_orderItem.getRowCount();
        for(int i=0;i<row;i++)
        {
        int id=Integer.parseInt( jTable_orderItem.getValueAt(i, 0).toString());
        String name=jTable_orderItem.getValueAt(i, 1).toString();
        String price=jTable_orderItem.getValueAt(i, 2).toString();
        String qty=jTable_orderItem.getValueAt(i, 3).toString();
        AddItemWaiter aiw=new AddItemWaiter();
        aiw.setId(id);
        aiw.setName(name);
        aiw.setPrice(price);
        aiw.setQty(qty);
        aiw.setWaiter_id(Global.waiter_id);
        aiw.setTable_id(Global.table_id);       // adding thai table id and waiter id in db of order as a foreignkey
        laiw.add(aiw);
        }
        OrderDAO odao=new OrderDAO();
        int count=odao.addOrder(laiw);
        if(count>0)
        {
            JOptionPane.showMessageDialog(null, "Order Recorded Sucessfully");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Order not recorded");
        }
    }//GEN-LAST:event_jButton_confirmOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_addItem;
    private javax.swing.JButton jButton_confirmOrder;
    private javax.swing.JButton jButton_loadMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_table;
    private javax.swing.JLabel jLabel_waiter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_orderItem;
    private javax.swing.JTable jTable_viewMenu;
    private javax.swing.JTextField jTextField_idMenu;
    private javax.swing.JTextField jTextField_itemName;
    private javax.swing.JTextField jTextField_price;
    private javax.swing.JTextField jTextField_qty;
    // End of variables declaration//GEN-END:variables
}
